Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: dev.liukaku.GetStopById
      CodeUri: C:\projects\java\metrolinkApi\metrolinkLamda
      Runtime: java17
      Architectures:
        - x86_64
      Environment:
        Variables:
          METRO_API_KEY: c444bf9c0004430f997ac3ded9cfb085